app:
  name: 2SOMEone-message

alimsg:
  region_id: cn-hangzhou
  access_key_id: <your access key id>
  access_key_secret: <your access key secret>

endpoint:
  # grpc 监听端口
  grpc_endpoint: <your endpoint>
  # http 默认监听端口
  api_endpoint: <your endpoint>

registry:
  address: <your endpoint>
